#!/usr/bin/python
import subprocess
import os
import sys

name = sys.argv[1]
test = name + 'Test'
base = 'data' + os.sep + test
cmd = 'ProtoMol ' + base + '.conf'
log = base + '.log'

stdout = stderr = open(log, 'w')
p = subprocess.Popen(cmd, shell = True, stdout = stdout, stderr = stderr)
p.wait()

for ext in sys.argv[2:]:
    output = 'data' + os.sep + test + '.' + ext

    if os.path.exists(output):
        print '%8d byte %s' % (os.stat(output).st_size, ext)
        #os.unlink(output)

    else:
        print 'ERROR no "' + output + '" file'
